### ISSUE TITLE
Is it Possible to run the .py file in the folder im getting error

### ISSUE THREAD

**Issue by LostiLama** [TobKra96/music_led_strip_control#143]
pi@Server2:/share/music_led_strip_control/server/libs/effects $ sudo python3 effect_fade.py
Traceback (most recent call last):
  File "/share/music_led_strip_control/server/libs/effects/effect_fade.py", line 1, in <module>
    from libs.effects.effect import Effect  # pylint: disable=E0611, E0401
ModuleNotFoundError: No module named 'libs.effects'

Getting this error when using a command to controll the effect i use nodered and it cant interface with the web ui is this possible

**Comment by Teraskull** [comment]
Running effects separately is not possible, because of how the module order is imported.
To control effects, the server `main.py` should be running, and changes should be made through the API.

NodeRed should call API endpoints instead of interacting with the UI.
You can find the API Documentation on the Web Interface sidebar.
