### ISSUE TITLE
server installation issue

### ISSUE THREAD

**Issue by shivamdev90** [TobKra96/music_led_strip_control#171]
i install lite version of os on rpi and started installing mlsc its is installed but the problems comes when i start the program by opening python3 main command terminal say modulenotfounderror:  no module names coloredlogs

please helps me out asap

**Comment by Teraskull** [comment]
Hi @shivamdev90,

First, please check the closed issues before creating another one. There were multiple questions about this.
Second, I don't know how you installed MLSC, because the script should install the modules automatically.

Anyways, go inside the `music_led_strip_control` directory and run the following:
```shell
sudo pip3 install -r requirements.txt
```

Then everything should work.
