### ISSUE TITLE
[Feature] Editing Current Lighting Effect and seemless changes

### ISSUE THREAD

**Issue by Marshalldog** [TobKra96/music_led_strip_control#178]
Is it possible that when you select an effect, the settings for the effect (eg. color, duration, blur etc) to appear at the bottom of the page, instead of having to go into the side menus every time???
Also is it possible, that once you press save (on the current effects settings) it smoothly transitions to the new settings instead of restarting the effect?

**Comment by Teraskull** [comment]
Hi @Marshalldog,

Unfortunately, seamless effect change is not possible because of how the effect queue works. On save, it reloads the effect animation.

Regarding moving the settings to the dashboard, this does not really fit into our vision, and would look out of place.
I just pushed a commit with a new feature to `dev_2.3` - 6b12a95016cb3870285b457e74079e3483237067.

When you hover over an effect button, there will be an "Edit" button in the top right corner, which will take you to the effect settings when clicked. I hope this is a fair compromise.

![image](https://user-images.githubusercontent.com/24798198/180581103-682185ed-3d92-4348-a8a8-cecd5b3f1b8c.png)
