### ISSUE TITLE
compatible with alexa or home assistent?

### ISSUE THREAD

**Issue by AndreXavier96** [TobKra96/music_led_strip_control#191]

**Comment by Teraskull** [comment]
Hi @AndreXavier96,

Regarding Alexa, not officially, since that would require us to pay a monthly fee for using AWS, but you could integrate it yourself using IFTTT for example, and call the API using the webhooks. Same with Google Assistant.

Home Assistant should also be the same, just calling API endpoints.

Thanks!

**Comment by AndreXavier96** [comment]
where can i see the api endpoints?

**Comment by Teraskull** [comment]
When you run MLSC, there is the API documentation link in the sidebar.
