### ISSUE TITLE
Tuya Lighting Integration

### ISSUE THREAD

**Issue by 42willow** [TobKra96/music_led_strip_control#192]
Possible option to add Tuya smart lights? I think most if not all of them are not individually addressable though.

**Comment by Teraskull** [comment]
Hi,

Unfortunately, we do not have plans to add any kind of integration, because it will add a lot of complexity, and there is no one to maintain it all. There are multiple different LED lights, like Tuya, Wiz, Philips, Wyze, and each of them has a different control method (bridge, UDP, Matter). This is why we have an API and documentation for MLSC if someone would like to, for example, control regular addressable LED strips through Google Assistant or Alexa. You can then use IFTTT to make API calls.

Thanks!
